export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';

export const CHANNEL_LIST = 'CHANNEL_LIST';
export const CHANNEL_ADD = 'CHANNEL_ADD';
export const CHANNEL_DEL = 'CHANNEL_DEL';
export const CHANNEL_PUT = 'CHANNEL_PUT';
export const CHANNEL_INFO = 'CHANNEL_INFO';


export const ACTIVITY_ADD = 'ACTIVITY_ADD';
export const ACTIVITY_INFO = 'ACTIVITY_INFO';
export const ACTIVITY_INDEX = 'ACTIVITY_INDEX';
export const ACTIVITY_PUT = 'ACTIVITY_PUT';
export const ACTIVITY_DEL = 'ACTIVITY_DEL';
export const ACTIVITY_RELEASE = 'ACTIVITY_RELEASE';
export const ACTIVITY_OFFLINE = 'ACTIVITY_OFFLINE';
export const ACTIVITY_GROUP_ADD = 'ACTIVITY_GROUP_ADD';
export const ACTIVITY_GROUP_INFO = 'ACTIVITY_GROUP_INFO';
export const ACTIVITY_GROUP_LIST = 'ACTIVITY_GROUP_LIST';
export const ACTIVITY_RULE_LIST = 'ACTIVITY_RULE_LIST';
export const ACTIVITY_RULE_DEL = 'ACTIVITY_RULE_DEL';

export const ACTIVITY_RULE_ADD_REGISTER = 'ACTIVITY_RULE_ADD_REGISTER';
export const ACTIVITY_RULE_ADD_CHANNEL = 'ACTIVITY_RULE_ADD_CHANNEL';
export const ACTIVITY_RULE_ADD_INVITE = 'ACTIVITY_RULE_ADD_INVITE';
export const ACTIVITY_RULE_ADD_INVITENUM = 'ACTIVITY_RULE_ADD_INVITENUM';
export const ACTIVITY_RULE_ADD_USERLEVEL = 'ACTIVITY_RULE_ADD_USERLEVEL';
export const ACTIVITY_RULE_ADD_BALANCE = 'ACTIVITY_RULE_ADD_BALANCE';
export const ACTIVITY_RULE_ADD_FIRSTCAST = 'ACTIVITY_RULE_ADD_FIRSTCAST';
export const ACTIVITY_RULE_ADD_CAST = 'ACTIVITY_RULE_ADD_CAST';

export const ARTICLE_TYPE_LIST = 'ARTICLE_TYPE_LIST';
export const ARTICLE_TYPE_ADD = 'ARTICLE_TYPE_ADD';
export const ARTICLE_TYPE_DEL = 'ARTICLE_TYPE_DEL';
export const ARTICLE_TYPE_PUT = 'ARTICLE_TYPE_PUT';
export const ARTICLE_TYPE_INFO = 'ARTICLE_TYPE_INFO';

export const ARTICLE_PUT = 'ARTICLE_PUT';
export const ARTICLE_ADD = 'ARTICLE_ADD';
export const ARTICLE_LIST = 'ARTICLE_LIST';
export const ARTICLE_DEL = 'ARTICLE_DEL';
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL';
export const ARTICLE_DETAIL_BY_ALIAS = 'ARTICLE_DETAIL_BY_ALIAS';