export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

// 接口请求
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

// 弹窗
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_HIDE = 'MODAL_HIDE';

// 渠道管理
export const CHANNEL_LIST = 'CHANNEL_LIST';
export const CHANNEL_ADD = 'CHANNEL_ADD';
export const CHANNEL_DEL = 'CHANNEL_DEL';
export const CHANNEL_PUT = 'CHANNEL_PUT';
export const CHANNEL_INFO = 'CHANNEL_INFO';

// 升级
export const APP_ADD = 'APP_ADD';
export const APP_PUT = 'APP_PUT';
export const APP_UPDATE_LOG = 'APP_UPDATE_LOG';
export const APP_INFO = 'APP_INFO';
export const APP_ENABLE = 'APP_ENABLE';
export const APP_DISABLE = 'APP_DISABLE';


// 活动
export const ACTIVITY_ADD = 'ACTIVITY_ADD';
export const ACTIVITY_INFO = 'ACTIVITY_INFO';
export const ACTIVITY_INDEX = 'ACTIVITY_INDEX';
export const ACTIVITY_PUT = 'ACTIVITY_PUT';
export const ACTIVITY_DEL = 'ACTIVITY_DEL';
export const ACTIVITY_RELEASE = 'ACTIVITY_RELEASE';
export const ACTIVITY_OFFLINE = 'ACTIVITY_OFFLINE';

export const ACTIVITY_GROUP_ADD = 'ACTIVITY_GROUP_ADD';
export const ACTIVITY_GROUP_INFO = 'ACTIVITY_GROUP_INFO';
export const ACTIVITY_GROUP_LIST = 'ACTIVITY_GROUP_LIST';
export const ACTIVITY_GROUP_DEL = 'ACTIVITY_GROUP_DEL';

export const ACTIVITY_RULE_LIST = 'ACTIVITY_RULE_LIST';
export const ACTIVITY_RULE_DEL = 'ACTIVITY_RULE_DEL';
export const ACTIVITY_RULE_ADD = 'ACTIVITY_RULE_ADD';


// 活动奖品
export const ACTIVITY_AWARD_ADD = 'ACTIVITY_AWARD_ADD';
export const ACTIVITY_AWARD_DEL = 'ACTIVITY_AWARD_DEL';
export const ACTIVITY_AWARD_LIST = 'ACTIVITY_AWARD_LIST';


// 奖品
export const AWARD_LIST = 'AWARD_LIST';
export const AWARD_ADD = 'AWARD_ADD';
export const AWARD_UPDATE = 'AWARD_UPDATE';
export const AWARD_DEL = 'AWARD_DEL';
export const AWARD_INFO = 'AWARD_INFO';
export const AWARD_ADD_TO_USER = 'AWARD_ADD_TO_USER';

export const ARTICLE_TYPE_LIST = 'ARTICLE_TYPE_LIST';
export const ARTICLE_TYPE_ADD = 'ARTICLE_TYPE_ADD';
export const ARTICLE_TYPE_DEL = 'ARTICLE_TYPE_DEL';
export const ARTICLE_TYPE_PUT = 'ARTICLE_TYPE_PUT';
export const ARTICLE_TYPE_INFO = 'ARTICLE_TYPE_INFO';
export const ARTICLE_TYPE_UP = 'ARTICLE_TYPE_UP';
export const ARTICLE_TYPE_DOWN = 'ARTICLE_TYPE_DOWN';

export const ARTICLE_PUT = 'ARTICLE_PUT';
export const ARTICLE_ADD = 'ARTICLE_ADD';
export const ARTICLE_LIST = 'ARTICLE_LIST';
export const ARTICLE_DEL = 'ARTICLE_DEL';
export const ARTICLE_DETAIL = 'ARTICLE_DETAIL';
export const ARTICLE_DETAIL_BY_ALIAS = 'ARTICLE_DETAIL_BY_ALIAS';
export const ARTICLE_RELEASE = 'ARTICLE_RELEASE';
export const ARTICLE_OFFLINE = 'ARTICLE_OFFLINE';
export const ARTICLE_UP = 'ARTICLE_UP';
export const ARTICLE_DOWN = 'ARTICLE_DOWN';

export const BANNER_LIST = 'BANNER_LIST';
export const BANNER_ADD = 'BANNER_ADD';
export const BANNER_PUT = 'BANNER_PUT';
export const BANNER_DEL = 'BANNER_DEL';
export const BANNER_ENABLE = 'BANNER_ENABLE';
export const BANNER_DISABLE = 'BANNER_DISABLE';
export const BANNER_UP = 'BANNER_UP';
export const BANNER_DOWN = 'BANNER_DOWN';
export const BANNER_INFO = 'BANNER_INFO';

export const ATTACHMENT_ADD = 'ATTACHMENT_ADD';
export const ATTACHMENT_LIST = 'ATTACHMENT_LIST';

export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_PROFILE = 'ACCOUNT_PROFILE';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
export const ACCOUNT_CAPTCHA = 'ACCOUNT_CAPTCHA';

export const STARTUP_LIST = 'STARTUP_LIST';
export const STARTUP_ADD = 'STARTUP_ADD';
export const STARTUP_ENABLE = 'STARTUP_ENABLE';
export const STARTUP_DISABLE = 'STARTUP_DISABLE';
export const STARTUP_PUT = 'STARTUP_PUT';
export const STARTUP_INFO = 'STARTUP_INFO';
export const STARTUP_DEL = 'STARTUP_DEL';
export const STARTUP_UP = 'STARTUP_UP';
export const STARTUP_DOWN = 'STARTUP_DOWN';

